use_frameworks!

platform :ios, '13.0'

target 'SwiftUISnapScroll_Example' do
  pod 'SwiftUISnapScroll', :path => '../'

  target 'SwiftUISnapScroll_Tests' do
    inherit! :search_paths

    
  end
end
